CREATE TABLE CUSTOMER(
custid VARCHAR2(6 CHAR),
pass VARCHAR2(20 CHAR) NOT NULL,
firstname VARCHAR2(30 CHAR) NOT NULL,
lastname VARCHAR2(30 CHAR),
address VARCHAR2(50 CHAR) NOT NULL,
city VARCHAR2(10 CHAR) NOT NULL,
state VARCHAR2(20 CHAR) NOT NULL,
pincode NUMBER(6) NOT NULL,
CONSTRAINT pk_cust PRIMARY KEY(custid),
CONSTRAINT ck_pass CHECK(LENGTH(pass) >= 8)
);

CREATE TABLE ACCOUNTDETAILS(
accountid VARCHAR2(6 CHAR) NOT NULL,
acctype VARCHAR2(10 CHAR) NOT NULL,
balance NUMBER(8) NOT NULL,
openingdate DATE DEFAULT SYSDATE,
CONSTRAINT pk_acc PRIMARY KEY(accountid),
CONSTRAINT fk_acc FOREIGN KEY (accountid) REFERENCES CUSTOMER(custid)
);

CREATE TABLE transactions(
accountfrom VARCHAR2(6 CHAR) NOT NULL,
accountto VARCHAR2(6 CHAR) NOT NULL ,
descrip VARCHAR2(30 CHAR) NOT NULL,
dateoftransaction DATE DEFAULT SYSDATE,
amount NUMBER(10) NOT NULL,
beforebal NUMBER(10) NOT NULL,
afterbal NUMBER(10) NOT NULL,
CONSTRAINT fk_trac1 FOREIGN KEY(accountfrom) REFERENCES ACCOUNTDETAILS(accountid),
CONSTRAINT fk_trac2 FOREIGN KEY(accountto) REFERENCES ACCOUNTDETAILS(accountid)
);

